### ISSUE TITLE
Saving Self Explanations. 

### ISSUE THREAD

**Issue by hmashrique** [aolney/self-explanation-extension#1]
**Issue:** When a user writes text , the text is orange. After saving, it becomes black. If user adds some more text , text color remains black. So users might get confused if they saved the 2nd time around.

**Possible solution** : 
1. Keep an edit button after saving first time.
2. Any unsaved text color should be orange.

**Comment by aolney** [comment]
Closed with https://github.com/aolney/self-explanation-extension/commit/69c7c12c95bb74f452f032a3495ad5a13b3cf8c1

Adding a single new keystroke makes orange again.
