### ISSUE TITLE
Reloading the page removes saved contents.

### ISSUE THREAD

**Issue by hmashrique** [aolney/self-explanation-extension#2]
**Issue:** 
After writing and saving self explanations , if the users reloads the URL , the saved texts gets removed from the text boxes.

**Comment by aolney** [comment]
Won't fix for reloading URL (page refresh) but re-running cell no longer clears unsaved explanation with https://github.com/aolney/self-explanation-extension/commit/69c7c12c95bb74f452f032a3495ad5a13b3cf8c1
